name = "obex-dns"
main = "src/index.ts"
compatibility_date = "2026-02-28"
compatibility_flags = ["nodejs_compat"]
# account_id = ""
minify = true

[assets]
directory = "./static"
binding = "ASSETS"

# D1 Database for Profiles, Rules and Logs
[[d1_databases]]
binding = "DB"
database_name = "obex_db"
database_id = "13d8c24f-064a-40d6-8b10-fa70bb3f79ab"

# KV Namespace for Cache (Deprecated, primary use Cache API)
# [[kv_namespaces]]
# binding = "CACHE_KV"
# id = ""

[triggers]
crons = ["0 * * * *"]

[placement]
mode = "targeted"
region = "aws:ap-southeast-1"

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true
head_sampling_rate = 0.3

[observability.traces]
enabled = true
head_sampling_rate = 0.05

[vars]
IP_REGION_APAC='[{"ip":"198.41.222.102","area":"SG"},{"ip":"173.245.59.246","area":"SG"},{"ip":"104.18.47.174","area":"HK"},{"ip":"104.19.50.3","area":"HK"}]'
IP_REGION_NAE='[]'
IP_REGION_NAW='[]'
IP_REGION_EU='[]'
